import type { Event } from "../model.js"
import type {
  ChatInput,
  MeetingSave,
  NewRecord,
  ParticipantInput,
  TranscriptInput,
  TranscriptRowInput,
} from "../store.js"

export const sampleEvent = (): NewRecord<Event> => ({
  eventSeriesId: null,
  title: "Example planning",
  description: null,
  location: null,
  startsAt: 1000,
  endsAt: 2000,
  timezone: "UTC",
  origin: "auto",
  deletedAt: null,
})
export const sampleMeeting = (): MeetingSave & {
  participants: [ParticipantInput]
  transcripts: [TranscriptInput & { rows: [TranscriptRowInput, ...TranscriptRowInput[]] }]
  chat: [ChatInput]
} => ({
  now: 3000,
  meeting: {
    accountId: 1,
    externalId: "example-occurrence",
    title: "Example planning",
    description: "Invented agenda",
    location: "Online",
    joinUrl: "https://example.com/room",
    startedAt: 1000,
    endedAt: 2000,
    durationMs: 1000,
    timezone: "UTC",
    hostIdentityId: null,
    participantsCount: 1,
    metadata: null,
    deletedAt: null,
    series: {
      externalId: "example-series",
      title: "Example planning",
      description: null,
      kind: "recurring",
      recurrence: null,
      hostIdentityId: null,
      joinUrl: "https://example.com/room",
      metadata: null,
      deletedAt: null,
    },
  },
  participants: [
    {
      identity: { provider: "example", externalId: "alice-example", name: "Alice Example", metadata: null },
      displayName: "Alice Example",
      email: "alice@example.com",
      role: "host",
      joinedAt: 1000,
      leftAt: 2000,
      durationMs: 1000,
      sessions: null,
      externalId: "alice-example",
      metadata: null,
    },
  ],
  transcripts: [
    {
      source: "api",
      format: "vtt",
      language: "en",
      contentHash: "invented-hash",
      externalCreatedAt: null,
      metadata: null,
      deletedAt: null,
      rows: [
        {
          position: 0,
          startMs: 0,
          endMs: 1000,
          speakerParticipantPosition: 0,
          speakerName: "Alice Example",
          text: "Ship the example plan.",
          normalizedText: null,
          metadata: null,
        },
      ],
    },
  ],
  chat: [
    {
      externalId: "example-chat",
      sentAt: 1500,
      senderParticipantPosition: 0,
      senderName: "Alice Example",
      recipient: "everyone",
      text: "Example chat",
      normalizedText: null,
      metadata: null,
    },
  ],
  summaries: [
    {
      source: "example-ai",
      title: "Example summary",
      overview: "Example overview",
      sections: [{ label: "Plan", text: "Example section" }],
      nextSteps: ["Example next step"],
      content: "Example content",
      docUrl: null,
      externalCreatedAt: null,
      externalUpdatedAt: null,
      metadata: null,
    },
  ],
  attachments: [
    {
      position: 0,
      kind: "file",
      mime: "text/plain",
      name: "example.txt",
      title: null,
      url: "https://example.com/file",
      size: 10,
      width: null,
      height: null,
      duration: null,
      providerRef: null,
      localPath: null,
      text: null,
      normalizedText: null,
      extraction: null,
      extractor: null,
      extractionError: null,
      contentSha256: null,
      extractedAt: null,
    },
  ],
})
